### ISSUE TITLE
Change Document Names from Arduino-Projects-and-Scripts to IoT-Projects-and-Scripts

### ISSUE THREAD

**Issue by SarthakSKumar** [SarthakSKumar/IoT-Projects-and-Scripts#10]
I recently changed the repo name from 'Arduino-Projects-and-Scripts' to 'IoT-Projects-and-Scripts'. I want this to reflect in the .md files and other documents in the repo.

**Comment by lsomacruzl** [comment]
can i please be assigned?

**Comment by SarthakSKumar** [comment]
Okay. Sure. Hope you know which are the files to be changed. If not, feel free to ask here.

**Comment by its-abhishek** [comment]
I would like to work on this issue

**Comment by SarthakSKumar** [comment]
@its-abhishek Okay. Sure. Hope you know which are files to be changed. If not, feel free to ask here. You have 24 hours starting from now.

**Comment by its-abhishek** [comment]
Changed Document Names from Arduino-Projects-and-Scripts to IoT-Projects-and-Scripts #10
