### ISSUE TITLE
Create a static website showing the list of projects in this repo. With a link to the respective folders

### ISSUE THREAD

**Issue by SarthakSKumar** [SarthakSKumar/IoT-Projects-and-Scripts#11]
Big work coming in. For now, a page with the repo details links to the projects in the repo. You can create another folder within the repo for the website.

**Comment by its-abhishek** [comment]
plss assign this work to me

**Comment by SarthakSKumar** [comment]
Sure. You have 24 hours to complete the issue, starting now.
