### ISSUE TITLE
Arduino-Intruder Alarm system

### ISSUE THREAD

**Issue by Sohoxic** [SarthakSKumar/IoT-Projects-and-Scripts#14]
I am going to make a simple obstacle sensing system with cheap parts like IR LED and photo diode.

**Comment by SarthakSKumar** [comment]
Sure. You can add this project as a subproject in this folder
https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects/Burglar%20Alarm
You have 24 Hours to complete this issue starting now.

**Comment by Sohoxic** [comment]
Will surely do that!!!
