### ISSUE TITLE
Light sensing system using arduino.

### ISSUE THREAD

**Issue by Sohoxic** [SarthakSKumar/IoT-Projects-and-Scripts#19]

**Comment by SarthakSKumar** [comment]
Could you please ellaborate on your issue?

**Comment by Sohoxic** [comment]
In this project, I'll design a simple light sensor that indicates when the light is indicated. When the LDR detects a light over certain intensity, the Arduino will trigger the buzzer. When the intensity of light decreases, the buzzer is turned off.

**Comment by SarthakSKumar** [comment]
There is a Smart Street Light Project under the repo, where I have used IR Sensors. You can add an approach using LDR, under the same project.
