### ISSUE TITLE
Update the website with new projects added in the repo

### ISSUE THREAD

**Issue by SarthakSKumar** [SarthakSKumar/IoT-Projects-and-Scripts#27]

**Comment by Lakshya-GG** [comment]
I want to work on issue number #27 , Please assign me this issue

**Comment by SarthakSKumar** [comment]
Okay. Go ahead. You have 24 hours starting now. Follow the current website template. You are free to add or improvise on the current website.

**Comment by satyamksharma** [comment]
Can you plz assign me to this i would like to contribute

**Comment by SarthakSKumar** [comment]
Hello. Yes, you can work on this issue. Wind it up, few hours before EOD if you wnt your contribution to reflect on hacktoberfest. @satyamksharma
