### ISSUE TITLE
Keyboard/Piano using arduino

### ISSUE THREAD

**Issue by Sohoxic** [SarthakSKumar/IoT-Projects-and-Scripts#28]

**Comment by SarthakSKumar** [comment]
Could you please elaborate on what you will be doing? @Sohoxic

**Comment by Sohoxic** [comment]
The arduino keyboard functions as a musical instrument which you can edit as you like. 
For eg: int A = 12; //Sixth button on pin 12. int a[] = {N_A5}; //Plays A Note

**Comment by SarthakSKumar** [comment]
Sure @Sohoxic . You have 24 hours starting from now
