### ISSUE TITLE
Broken Link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by gregoris-io** [SarthakSKumar/IoT-Projects-and-Scripts#29]
<h3>Broken link in the subsection:</h3>  

![image](https://user-images.githubusercontent.com/71711222/198498907-9b9a2dd9-1fcb-47af-9c1b-67ceacaab864.png)

Following the link, I am brought to:  
![image](https://user-images.githubusercontent.com/71711222/198499000-86b1b036-3460-43ad-8397-c2a07a89b36f.png)

<b>Is the intention to direct users to the Website repository, or the actual website? <b>

**Comment by gregoris-io** [comment]
@SarthakSKumar, I would be more than happy to correct this issue for you upon further instruction.

Thanks, Mitch

**Comment by SarthakSKumar** [comment]
Hello @gregoris-io . Thanks for bringing this to my notice. I want the link to redirect to the website, whose link is in the description of this repo. I shall assign this to you. Are you a hacktoberfest participant?

**Comment by gregoris-io** [comment]
@SarthakSKumar , I will gladly accept the assignment, and yes I am a hacktoberfest participant.

**Comment by SarthakSKumar** [comment]
Okay. You have 24 hours starting from now. Good Luck! @gregoris-io
