### ISSUE TITLE
Measuring Temperature and Humidity with DHT22 on a ESP32

### ISSUE THREAD

**Issue by adithya-s-k** [SarthakSKumar/IoT-Projects-and-Scripts#30]
---
Title: Measuring Temperature and Humidity with DHT22 on a ESP32
About: i will be using the DHT22 sensor to measure temperature and humidity
Name: Adithya S Kolavi
Label: Feature Request
Assignee: [adithya-s-k](https://github.com/adithya-s-k)

---

Define You:

- [x] Hacktoberfest Participant 
- [x] Contributor

**Comment by SarthakSKumar** [comment]
Sure. You can work on this. You have 24 hours starting now @adithya-s-k
