### ISSUE TITLE
Self Activating Night Lamp using Arduino

### ISSUE THREAD

**Issue by Lakshya-GG** [SarthakSKumar/IoT-Projects-and-Scripts#34]
Using components such as 
Breadboard , Arduino Uno R3 ,LED , Resistor ,LDR(Photo Resistor)
creating a Night lamp (LED) which automatically lights up by sensing the darkness.

**Comment by SarthakSKumar** [comment]
There is a similar project in the repo, using LDR. Only the Use Case is different.
