### ISSUE TITLE
Add buttons to website, above the footer. 

### ISSUE THREAD

**Issue by SarthakSKumar** [SarthakSKumar/IoT-Projects-and-Scripts#40]
![image](https://user-images.githubusercontent.com/81763561/199008576-8cb05f33-3ea9-4281-a664-d205754975f0.png)
To something like this maybe. Or something even better. All up to your creativity.

**Comment by satyamksharma** [comment]
Hi there i would like to work on this change. Assign me

**Comment by SarthakSKumar** [comment]
Sure @satyamksharma . Complete it a few hours before Hacktoberfest ends today, to make it count.
