### ISSUE TITLE
Work on ESP Project Tab not working in website

### ISSUE THREAD

**Issue by SarthakSKumar** [SarthakSKumar/IoT-Projects-and-Scripts#53]

**Comment by its-abhishek** [comment]
i want work on this plss assign me @SarthakSKumar

**Comment by SarthakSKumar** [comment]
Cannot assign multiple issues at once. Please resolve the previous issue before applying to this issue.

**Comment by its-abhishek** [comment]
I have completed the previous issue can you assign me now @SarthakSKumar

**Comment by SarthakSKumar** [comment]
Assigned  @its-abhishek
