### ISSUE TITLE
Add Contributor Profile Images to the website.

### ISSUE THREAD

**Issue by SarthakSKumar** [SarthakSKumar/IoT-Projects-and-Scripts#54]
Should reflect on the website, when new contributors contribute to this repo.

**Comment by its-abhishek** [comment]
i want work on this plss assign me @SarthakSKumar

**Comment by SarthakSKumar** [comment]
Cannot assign multiple issues at once. Please resolve the previous issue before applying to this issue.

**Comment by its-abhishek** [comment]
i want work on this plss assign me @SarthakSKumar

**Comment by SarthakSKumar** [comment]
Assigned @its-abhishek
