### ISSUE TITLE
Refactoring the website of IoT projects and script

### ISSUE THREAD

**Issue by satyamksharma** [SarthakSKumar/IoT-Projects-and-Scripts#59]
**Define You**

- [ ] Hacktoberfest Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
This is more of a complete new website with changed design and UI

**Describe the solution you'd like...**
I have refactored the website to look clean and beautiful

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by SarthakSKumar** [comment]
Assigned @satyamksharma. Please include issue number of the previous assigned issue also, in the PR.

**Comment by SarthakSKumar** [comment]
Issue not resolved with PR #60 @satyamksharma
