### ISSUE TITLE
Add footer to website

### ISSUE THREAD

**Issue by SarthakSKumar** [SarthakSKumar/IoT-Projects-and-Scripts#66]
Add a footer to the website, consisting of links in the header, the repo name, maintainer details, github repo link and maintainer profile link. Make it match the current UI of the website

**Comment by satyamksharma** [comment]
Hi there i would like to add the footer. Just mention the contents you want in the footer

**Comment by SarthakSKumar** [comment]
Please resolve the previous issue before being assigned to a new issue @satyamksharma
