### ISSUE TITLE
Bug: Circuit Images don't load for a few project cards

### ISSUE THREAD

**Issue by SarthakSKumar** [SarthakSKumar/IoT-Projects-and-Scripts#67]

**Comment by HritikR** [comment]
This issue is due to missing image link
https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/blob/12f5bf60a2ecefd62cc73f626a6ad3c9d489f0dd/Website/public/cards.json#L182-L187

**Comment by SarthakSKumar** [comment]
Any updates @HritikR ?
