### ISSUE TITLE
Feat: Add an Arduino project that counts number of button pushes

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [SarthakSKumar/IoT-Projects-and-Scripts#69]
**Define You**

- [ ] Hacktoberfest Participant 
- [x] Contributor

**Is your feature request related to a problem? Please describe.**
This project will have a push button and the number of times it is pushed can be counted.

**Describe the solution you'd like...**
An arduino project for the same

**Comment by SarthakSKumar** [comment]
Please add more details about the project you would like to add. 
Follow the Issue template.

**Comment by Soumya-Kushwaha** [comment]
Edited @SarthakSKumar

**Comment by SarthakSKumar** [comment]
Assigned @Soumya-Kushwaha
