### ISSUE TITLE
Work on the README.md file for the Repository

### ISSUE THREAD

**Issue by SarthakSKumar** [SarthakSKumar/IoT-Projects-and-Scripts#7]
Come up with a good README.md for the project. You can make use of creative badges, stats anything. Its up to your creativity :)

**Comment by ManasiGDeshmukh** [comment]
Manasi Deshmukh
Cummins college of engineering for women
Dept: Computer Engineering
I would like to work on this issue.
Can you please assign me this issue?

**Comment by SarthakSKumar** [comment]
Sure. You have 24 hours to complete the issue before I re-assign it to someone else

**Comment by SarthakSKumar** [comment]
Any Update @ManasiGDeshmukh ?

**Comment by ManasiGDeshmukh** [comment]
@SarthakSKumar working on it..
