### ISSUE TITLE
Bug: Website Navbar Links not Working

### ISSUE THREAD

**Issue by SarthakSKumar** [SarthakSKumar/IoT-Projects-and-Scripts#77]

**Comment by Preetraj2002** [comment]
can you elaborate more on this

**Comment by SarthakSKumar** [comment]
![image](https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/assets/81763561/a2cd06d5-976c-49e3-9b08-75519b3b637c)

Hi @Preetraj2002 
So here, when the 'Arduino' Link is clicked, the list of Arduino projects should get filtered and displayed, and a similar thing should take place when 'ESP' is clicked.
