### ISSUE TITLE
Bug: Fix footer links not working

### ISSUE THREAD

**Issue by SarthakSKumar** [SarthakSKumar/IoT-Projects-and-Scripts#78]

**Comment by Preetraj2002** [comment]
@SarthakSKumar can you specify which link is not working. I have tested the site, I see 4 links are working fine and other 2 legal links have no webpages.

**Comment by SarthakSKumar** [comment]
Hi @Preetraj2002 
The existing sections need to be removed from the footer. 
New sections to be created in the footer:

'Contributing'
1. Code of Conduct: https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/blob/master/CODE_OF_CONDUCT
2. Guidelines: https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/blob/master/CONTRIBUTING.md

'About'
1. About Repo: https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/blob/master/README.md
2. Maintainer: https://github.com/SarthakSKumar

'Projects'
1. Arduino Projects: https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/Arduino%20Projects
2. ESP Projects: https://github.com/SarthakSKumar/IoT-Projects-and-Scripts/tree/master/ESP%20Projects

The social links and icons have to be removed as well.

**Comment by Preetraj2002** [comment]
I have updated the footer. Please review it.

**Comment by SarthakSKumar** [comment]
Hi @Preetraj2002 
Please don't create PR's until an issue is assigned to you. Assigning now. Will review the PR

**Comment by Preetraj2002** [comment]
Sure. I always do wait till I am assigned a task but few org don't formally assign so I thought you would just review it. Will make sure next time :)
