### ISSUE TITLE
Adding ESP folder and ESP32 led blink code

### ISSUE THREAD

**Issue by adithya-s-k** [SarthakSKumar/IoT-Projects-and-Scripts#8]
---
Title: ESP32 inbuilt blink
About: writing a program with ESP32 to blink the LED and set the time interval at which it blinks
Name: Adithya S Kolavi
Label: Feature Request
Assignee: '[adithya-s-k](https://github.com/adithya-s-k)'

---

Define You:

- [x] Hacktoberfest Participant 
- [x] Contributor

Is your feature request related to a problem? Please describe.
Blinking LED is the first project which helps set up the microcontroller, this will help check if everything is fine with the ESP32

**Comment by SarthakSKumar** [comment]
Sure. You can work on this issue. You have 24 hours to complete this issue, starting now.
