### ISSUE TITLE
Add Water Monitoring System using Arduino

### ISSUE THREAD

**Issue by anubhav1433** [SarthakSKumar/IoT-Projects-and-Scripts#82]
Water Monitoring System monitors the water level using ultrasonic sensor and as per the specified distance the beeper starts beeping indicating the the condition being satisfied and esp32 wifi module helps to get notification of the same in the user's mobile phone. The Application of this system can be monitoring water tank at home avoiding overflow and wastage of water.

**Comment by SarthakSKumar** [comment]
Could you please elaborate on the issue? @anubhav1433
